services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # We could have Dockerfile.dev & Dockerfile.prod (with builder and final), instead of one Dockerfile multistage
      target: dev
    container_name: rest-server
    hostname: rest-server
    depends_on:
      - db
    env_file: ".env"
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app  # Monta el código fuente de tu proyecto en el contenedor
      -  ./.env:/usr/src/app/.env  # Montar el archivo .env en el contenedor
    
    # Si en "target" ponemos "final" en vez de "dev", entonces hay que descomentar la linea del "command"
    # En vez de este comando podriamos configurar docker-compose con healthschecks (investigar mas)
    # command: ["sh", "-c",
    #            "echo 'Waiting for database...';
    #            timeout 60 sh -c 'until pg_isready -h db -p 5432; do sleep 1; done';
    #            exec /usr/local/bin/restaurant_system"]
    
    # deploy:
    #   restart_policy:
    #     condition: on-failure

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    hostname: db

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # sets the superuser password for PostgreSQL. This env variable is necessary to use the postgres image.
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
