version: '3.8'

services:
  app:
    build:
      context: .
    container_name: rest-server
    hostname: rest-server
    # networks:
    #   - dinamita_network
    depends_on:
      - db
    environment:
      - PGUSER=${DB_USER:-postgres}
      - PGPASSWORD=${DB_PASSWORD:?database password not set}
      - PGHOST=${DB_HOST:-db}
      - PGPORT=${DB_PORT:-5432}
      - PGNAME=${DB_NAME:-tdl_dinamita}
    ports:
      - 8080:8080
    # En vez de este comando podriamos configurar docker-compose con healthschecks (investigar mas)
    command: ["sh", "-c", "echo 'Waiting for database...'; timeout 60 sh -c 'until pg_isready -h tdl_dinamita -p 5432; do sleep 1; done'; exec /restaurant_system"]
    # deploy:
    #   restart_policy:
    #     condition: on-failure

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    hostname: database
    # networks:
    #   - dinamita_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # sets the superuser password for PostgreSQL. This env variable is necesary to use the postgres image.
      #POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:

# networks:
#   dinamita_network:
#     driver: bridge
