DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tables CASCADE;
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS time_slots CASCADE;
DROP TABLE IF EXISTS dishes CASCADE;