// Code generated by mockery v2.46.3. DO NOT EDIT.

package service

import (
	context "context"

	models "github.com/agus-germi/TDL_Dinamita/internal/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// AddTable provides a mock function with given fields: ctx, tableNumber, seats, location
func (_m *MockService) AddTable(ctx context.Context, tableNumber int64, seats int64, location string) error {
	ret := _m.Called(ctx, tableNumber, seats, location)

	if len(ret) == 0 {
		panic("no return value specified for AddTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string) error); ok {
		r0 = rf(ctx, tableNumber, seats, location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddUserRole provides a mock function with given fields: ctx, userID, roleID
func (_m *MockService) AddUserRole(ctx context.Context, userID int64, roleID int64) error {
	ret := _m.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for AddUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoginUser provides a mock function with given fields: ctx, email, password
func (_m *MockService) LoginUser(ctx context.Context, email string, password string) (*models.User, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.User, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.User); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterUser provides a mock function with given fields: ctx, name, password, email
func (_m *MockService) RegisterUser(ctx context.Context, name string, password string, email string) error {
	ret := _m.Called(ctx, name, password, email)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, name, password, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveReservation provides a mock function with given fields: ctx, userID, tableNumber, date
func (_m *MockService) RemoveReservation(ctx context.Context, userID int64, tableNumber int64, date time.Time) error {
	ret := _m.Called(ctx, userID, tableNumber, date)

	if len(ret) == 0 {
		panic("no return value specified for RemoveReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, time.Time) error); ok {
		r0 = rf(ctx, userID, tableNumber, date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveTable provides a mock function with given fields: ctx, tableNumber
func (_m *MockService) RemoveTable(ctx context.Context, tableNumber int64) error {
	ret := _m.Called(ctx, tableNumber)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, tableNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveUser provides a mock function with given fields: ctx, email
func (_m *MockService) RemoveUser(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveUserRole provides a mock function with given fields: ctx, userID
func (_m *MockService) RemoveUserRole(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReserveTable provides a mock function with given fields: ctx, userID, tableNumber, date
func (_m *MockService) ReserveTable(ctx context.Context, userID int64, tableNumber int64, date time.Time) error {
	ret := _m.Called(ctx, userID, tableNumber, date)

	if len(ret) == 0 {
		panic("no return value specified for ReserveTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, time.Time) error); ok {
		r0 = rf(ctx, userID, tableNumber, date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
